test:
  clients:
    default:
      database: micro_learning_test_db
      hosts:
        - localhost:27017

development:
  clients:
    default:
      database: micro_learning_dev_db
      hosts:
        - localhost:27017

production:
  clients:
    default:
      url: <%= ENV['DATABASE_URL'] %>
