test:
  clients:
    default:
      database: micro_learning_test_db
      hosts:
        - localhost:27017

development:
  clients:
    default:
      database: micro_learning_dev_db
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: <%= ENV['DATABASE_NAME'] %>
      hosts:
        - ds239911.mlab.com:39911
      options:
        - user: <%= ENV['DATABASE_USER'] %>
        - password: <%= ENV['DATABASE_PASSWORD'] %>
